language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
script:
- cd 2-repositories/scala-repo-server
- ./scripts/create-test-user.bash
- sbt test
- cd ../..
deploy:
- provider: script
  skip_cleanup: true
  script: ./.travis/deploy.py
  on:
    condition: '"$(.travis/is_core_release_tag.sh $TRAVIS_TAG)" == "" && $? == 0'
    tags: true
- provider: script
  skip_cleanup: true
  script: ./.travis/deploy.py
  on:
    condition: '"$(.travis/is_schemaddl_release_tag.sh $TRAVIS_TAG)" == "" && $? == 0'
    tags: true
- provider: script
  skip_cleanup: true
  script: ./.travis/deploy.py
  on:
    condition: '"$(.travis/is_igluctl_release_tag.sh $TRAVIS_TAG)" == "" && $? == 0'
    tags: true
env:
  global:
  - secure: D5Egj4tqCXpL7H4x/BsPs9tOVX7Q20ooaB5e7+KDBk9PdLFFLHGMJP6+lRjmLNnX89ngWSNmPyu9L5qJ8D4Bmuy+s2bMN8iM/bryJrGvAMUjLXnVEaENn4hd7Xn6zA0JoTvyk8jEiLlTsZakpz8j8N6g9mscZXsMoXtRWFOnE0s=
  - secure: NuQTaOT/cgld8PE6QWAKiEFQcxmOJ46Gfq7hyNVte2fRICfkOz531mnPNcX5Zak+Z1S1gW4xDHxo7cV3Fa4KVZ5vp/MP10BBwjG5u1x+s4pLoGGZGWSpBnGIQED8KcBKrsywLJEPR6ohYcOSj6cvyOWrbKTEntBpxYy+WdygJsQ=
  - secure: DdUD2lASdBYuTK7CYMf+F3iNTCxLKnfuS4EjpWMovwFtqYEsaexf3ozukBnDc+8qqJvaytxAby9VDJ7sahIvQzoUXcWatWQPVoo18qglJCpl3VaCRkSXzMouL2KQxFEcnH6NCOG9YsYBxtFBqhM9Y9UeG1S3d1DXHqmXos3jSws=
  - secure: JycPiwXieJVIgpN1O1tJrnK3UPeq0JICe2MYVylMSVK4/VxxpvA8a9Op1DOb8yYg5Jws1t48nmJaiW+vseiIU2AD/9I2YKZ7dAuU8MgGe644QvCXiy/H3KNw7vO5G0zHJuRmVGvzIrCqv34OKp+V9jk3zXclJEB7csqlt1PSkcE=
  - secure: J4P9lwDqK0vcKOSsLodMOH2ob8lRySQCyK3gBZ4dQ23lMw3AvnuHO4OlZoBgO6l5We2dSJMduDq8cLvSvV7sZwmSEesz2VUgnaT87ciDG4yi+TWqebbvGkV/gkvoVhe6AnIOx9sM8WLg5XdwFpZoV6Ss6QLImG+Tg4xrxJr7nCU=
  - secure: PlkOwsrnw7u1LmLsdOabxCTmHWoziFy3rQCMbbykOyhKE9QutobONYSVJinQ0LnkCorXd+asr8EfyC+UCAUqyPVWnzF+OLUrcHGgcsIlxuNH6sBkuqpufH0jc526uYDIpR0tSvCrQLRc4ZtP456cBBflPeb2Qy3BYt5BVapGusg=
