# Required: local settings
local:
  root_dir : <%= ENV['TRAVIS_BUILD_DIR'] %>

# Required: deployment targets
targets:
  - type     : "bintray"
    user     : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_USER'] %>
    password : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_API_KEY'] %>

# Required: packages to be deployed
packages:
  - repo     : "snowplow-generic"
    name     : "igluctl"
    user_org : "snowplow"
    publish  : true
    override : false
    continue_on_conflict : false
    version  : <%= FUNC['sbt_version(0-common/igluctl/)'] %>
    build_version : <%= ENV['TRAVIS_BUILD_RELEASE_TAG'] %>
    build_commands:
      - cd 0-common/scala-core && sbt test --warn && sbt publishLocal && cd ../..
      - cd 0-common/scala-core && sbt "project igluCoreCirce" test --warn && sbt "project igluCoreCirce" publishLocal --warn && cd ../..
      - cd 0-common/scala-core && sbt "project igluCoreJson4s" test --warn && sbt "project igluCoreJson4s" publishLocal --warn && cd ../..
      - cd 0-common/schema-ddl && sbt test --warn && sbt publishLocal && cd ../..
      - cd 0-common/igluctl && sbt assembly && cd ../..

    # Required: Artifact
    artifacts:
      - prefix : "igluctl_"
        suffix : ""
        type   : "zip"

        # The binaries to put in the zip
        binary_paths:
          - 0-common/igluctl/target/scala-2.12/igluctl-{{ packages.0.build_version }}.jar
